<?php

namespace Tests\Feature\ComponentTest;

use App\Http\Controllers\Api\Components\Jwt\PostJwtRegisterAction;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\Artisan;
use Tests\TestCase;

class PostJwtRegisterActionTest extends TestCase
{
    use WithFaker;
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Artisan::call('migrate');
    }
    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_register_action()
    {
        $reg_data = [
            'fullname' => $this->faker->name,
            'username' => $this->faker->name,
            'phone'    =>  randomPhone(),
            'password' => '32132332321123',
        ];
        PostJwtRegisterAction::execute($reg_data);
        $this->assertEquals(1, User::get()->count());
        $this->assertTrue(! auth()->check());
    }
}
