<?php

namespace Tests\Feature;

use App\Http\Controllers\Api\Components\Friend\PostFriendAddAction;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\Artisan;
use Tests\TestCase;

class PostFriendAddActionTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Artisan::call('migrate');
    }
    /**
     * A basic feature test example.
     * @test
     * @return void
     */
    public function test_add_new_friend()
    {
        User::factory(4)->create();
        $sender = User::find(1);
        $recipient = User::find(2);
        $middleMan = User::find(3);
        $forthMan = User::find(4);
        $this->actingAs($sender);
        PostFriendAddAction::execute(['email' => $recipient->email]);
        PostFriendAddAction::execute(['email' => $recipient->email]);
        PostFriendAddAction::execute(['email' => $middleMan->email]);
        PostFriendAddAction::execute(['email' => $forthMan->email]);
        $this->assertEquals(3, $sender->friends->count());
        $this->assertEquals(1, $middleMan->friends->count());
    }
}
