<?php

namespace Tests\Feature;

use App\Models\Group;
use App\Models\Message;
use App\Models\User;
use App\Repositories\DB\GroupDB;
use App\Repositories\DB\MessageDB;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Tests\TestCase;

class MessageTest extends TestCase
{
    use WithFaker;
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Artisan::call('migrate');

    }

    /**
     * A basic feature test example.
     * @test
     * @return void
     */
    public function user_can_create_message()
    {
        User::factory(2)->create();
        $sender = User::find(1);
        $recipient = User::find(2);
        $this->actingAs($sender);
        $this->actingAs($recipient);
        $data = [
            'body' => $this->faker->sentence,
            'sender_id' => $sender->id,
            'recipient_id' => $recipient->id
        ];
        MessageDB::createNewMessage($data['body'], $data['recipient_id'] , $data['sender_id']);
        $this->assertEquals(1, Message::get()->count());
    }

    /**
     * @test
     */
    public function user_can_create_group()
    {
        User::factory(2)->create();
        User::factory(2)->create();
        $sender = User::find(1);
        $recipient = User::find(2);
        $this->actingAs($sender);
        $this->actingAs($recipient);
        $group = GroupDB::createGroup('teddy');
        GroupDB::attachUserToAGroup($group, [$sender->id, $recipient->id]);
        $this->assertEquals(1, Group::get()->count());
        $this->assertEquals(2, DB::table('group_user')->count());
    }

    /**
     * @test
     */
    public function user_can_create_group_message()
    {
        User::factory(2)->create();
        $sender = User::find(1);
        $recipient = User::find(2);
        $this->actingAs($sender);
        $this->actingAs($recipient);
        $group = Group::query()->create([
            'name' => 'Teddy',
            'owner_id' => $sender->id
        ]);
        $data = [
            'body' => $this->faker->sentence,
            'sender_id' => $sender->id,
            'group_id' => $group->id
        ];
        MessageDB::createNewGroupMessage($data['body'], $data['group_id'] , $data['sender_id']);
        $this->assertEquals(1, Message::get()->count());
    }
}
