<?php

namespace Tests\Feature;

use App\Events\NewAdminMessageEvent;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Auth;
use Predis\Client;
use Tests\TestCase;

class NotifTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Artisan::call('migrate');
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_example()
    {
        $c = new Client();
        $u = User::create([
            'name' => 'teddy',
            'email' => 's23.mg@gmail.com',
            'password' => bcrypt(123321)
        ]);
        $this->actingAs($u);
        NewAdminMessageEvent::dispatch(Auth::user());
    }
}
