<?php

namespace Tests\Feature\HTTPTest;

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\Artisan;
use Tests\Feature\HttpHelper;
use Tests\TestCase;

class ChannelRouteTest extends TestCase
{
    use WithFaker;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Artisan::call('migrate');
        $data = [
            'fullname' => $this->faker->name,
            'username' => $this->faker->name,
            'email' => $this->faker->email,
            'password' => '32132332321123',
            'password_confirmation' => '32132332321123',
            '_token' => csrf_token()
        ];
        $this->post('/register', $data);
    }

    /**
     * @test
     */
   public function create_channel_route()
   {
       User::factory(3)->create();
       $sender = User::find(1);
       $recp = User::find(2);
       $mid = User::find(3);
       $res = $this->post(route('channel.create'), ['type' => 'solo', 'recipient_id' => $recp->id])
           ->assertOk();
   }

    /**
     * @test
     */
    public function read_channel_route()
    {
        User::factory(3)->create();
        $sender = User::find(1);
        $recp = User::find(2);
        $mid = User::find(3);
        $res = $this->get(route('channel.read'))
            ->assertOk();
    }
}
